services:
  server:
    build: ./server
    ports:
      - '5000:5000'
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env
  # database service
  db:
    image: mysql:5.7
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: Habte1435691
      MYSQL_DATABASE: authz
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
